-- =====================================================================
-- cart_reservations — 주문서 담기 재고 홀드(예약) 테이블 (2026-07-06)
--
-- 목적: 고객이 주문서에 상품을 담는 순간 "선점(홀드)"을 기록해서
--   다른 고객 화면·품절 판정에 즉시 차감으로 반영. 15분 지나면 자동 무효
--   (담고 이탈한 고객의 재고 영구 잠김 방지). 담아두고 페이지를 보고 있으면
--   45초 하트비트로 계속 연장됨.
--
-- ⚠️ 진짜 재고(products.stock / product_note.stock_variants)는 절대 건드리지 않음.
--    실제 차감 = 기존 주문제출 RPC / 복구 = 기존 취소 복구 RPC (완전 무변경).
--    이 테이블은 "표시용 선점"만 담당 — 지워져도 주문/돈에 영향 0.
--
-- 접근: RLS 활성 + 정책 없음 = anon/authenticated 직접 접근 차단.
--       서버(app/api/cart-reservations, service_role)만 읽고 씀.
-- =====================================================================

create table if not exists cart_reservations (
  id bigint generated by default as identity primary key,
  session_key text not null,
  customer_phone text,
  product_id text not null,
  color text not null default '',
  size text not null default '',
  qty integer not null default 0,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists cart_reservations_product_idx on cart_reservations (product_id);
create index if not exists cart_reservations_session_idx on cart_reservations (session_key);
create index if not exists cart_reservations_expires_idx on cart_reservations (expires_at);

alter table cart_reservations enable row level security;
-- 정책을 만들지 않음 → anon 키로는 접근 불가(서버 service_role 전용)

-- (선택) 만료 행 청소 — 조회는 항상 expires_at > now() 조건이라 안 지워도 정확함.
-- 쌓이는 게 신경 쓰이면 가끔 실행: delete from cart_reservations where expires_at < now() - interval '1 day';
