-- ============================================================================
-- live_alert_recipients — 방송알림 수신자 기록 (2026-07-08)
-- ============================================================================
-- 목적: 방송알림(알림톡)을 "누가 받았는지" 방송별로 기록 → 재발송 시 이미 받은 사람 제외(증분 발송).
--   - 재발송 완전차단 대신, 안 받은 사람에게만 보냄. 전체/신청자 모드 모두 이미 받은 사람 자동 제외.
-- 규칙: 추가만(ADD) · IF NOT EXISTS(재실행 안전) · 기존 데이터 무변경.
-- 보안: 서버(service_role)만 접근. RLS 켜고 정책 없음 = anon 차단(상품 RLS 교훈 반영).
-- ▶ ⚠️ 코드 배포보다 먼저 실행 권장(없어도 크래시는 안 나지만 증분제외/기록이 동작 안 함).
-- 돈 로직 무관.

create table if not exists public.live_alert_recipients (
  id            bigint generated by default as identity primary key,
  broadcast_id  text not null,
  customer_phone text not null,
  status        text not null default 'success',
  sent_at       timestamptz not null default now()
);

-- 방송별 1인 1행(중복 기록 방지 + upsert ignoreDuplicates 근거)
create unique index if not exists live_alert_recipients_uidx
  on public.live_alert_recipients (broadcast_id, customer_phone);
create index if not exists live_alert_recipients_bc_idx
  on public.live_alert_recipients (broadcast_id);

alter table public.live_alert_recipients enable row level security;
-- 정책 없음 = anon 차단. 서버(service_role)는 RLS 우회하므로 발송 route는 정상.
