export type ProductLike = Record<string, unknown>;
export type DetailProduct = {
  parentId: string; parentName: string; detailName: string; code: string; hidden: boolean;
  price: number; images: string[]; image: string; colors: string[]; sizes: string[];
  stockManaged: boolean; stockVariants: Array<{ color: string; size: string; stock: number }>; stock: number | null;
};
const EMPTY = new Set(["", "없음", "없슴", "무", "-", "none", "n/a", "na"]);
export function cleanOptionValues(raw: unknown): string[] {
  const values = Array.isArray(raw) ? raw : typeof raw === "string" ? (() => { const t=raw.trim(); if(!t)return []; if(t.startsWith("[")&&t.endsWith("]")){try{const p=JSON.parse(t); return Array.isArray(p)?p:[t];}catch{return t.split(/[,|]+/g);}} return t.split(/[,|]+/g);})() : [];
  return [...new Set(values.map(v=>String(v??"").trim()).filter(v=>!EMPTY.has(v.toLowerCase())))];
}
export function parseProductNote(row: ProductLike|null|undefined): Record<string, unknown> { if(!row)return {}; const raw=row.product_note; if(raw&&typeof raw==="object"&&!Array.isArray(raw))return raw as Record<string,unknown>; if(typeof raw==="string"&&raw.trim()){try{const p=JSON.parse(raw); return p&&typeof p==="object"&&!Array.isArray(p)?p:{};}catch{return {};}} return {}; }
function str(row:ProductLike,keys:string[]){for(const k of keys){const v=row[k]; if(typeof v==="string"&&v.trim())return v.trim(); if(typeof v==="number"&&Number.isFinite(v))return String(v);} return "";}
function num(row:ProductLike,keys:string[]){for(const k of keys){const v=row[k]; if(typeof v==="number"&&Number.isFinite(v))return v; if(typeof v==="string"){const n=Number(v.replace(/[^0-9.-]/g,"")); if(Number.isFinite(n))return n;}}return 0;}
function rec(v:unknown):Record<string,unknown>{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function arr(v:unknown):string[]{return Array.isArray(v)?v.map(x=>String(x??"").trim()).filter(Boolean):[];}
export function detailPricePresentation(basePrice: unknown, surcharge: unknown) {
  const base = Math.max(0, Math.floor(Number(basePrice) || 0));
  const plus = Math.max(0, Math.floor(Number(surcharge) || 0));
  const actualPrice = base + plus;
  return {
    actualPrice,
    actualLabel: `${actualPrice.toLocaleString("ko-KR")}원`,
    surcharge: plus,
    surchargeLabel: `+${plus.toLocaleString("ko-KR")}원`,
  };
}
export function detailCode(name:string){const clean=String(name||"").trim(); const m=clean.match(/^([A-Za-z]+)(?:\([^)]*\))?-(\d+[A-Za-z]*)/); return m?`${m[1].toUpperCase()}-${m[2].toUpperCase()}`:(clean.split(/\s+/)[0]||clean);}
export function isBrandGroup(row:ProductLike){const g=rec(parseProductNote(row).brand_group);return g.enabled===true;}
export function detailNamesForProduct(row:ProductLike,includeHidden=true){const note=parseProductNote(row); if(!isBrandGroup(row)&&note.combo_mode!==true)return []; const axes=Array.isArray(note.option_axes)?note.option_axes as Array<Record<string,unknown>>:[]; const axis=axes.find(a=>String(a?.key||"")==="detail")||axes[0]; const group=rec(note.brand_group); const hidden=new Set(arr(note.combo_hidden)); const all=[...new Set([...arr(axis?.values),...arr(note.combo_detail_values),...Object.keys(rec(group.detail_options)),...(Array.isArray(row.color_options)?arr(row.color_options):[])].filter(Boolean))]; return includeHidden?all:all.filter(n=>!hidden.has(n));}
function directImage(row:ProductLike){const d=str(row,["image_url","cover_image_url","main_image_url","thumbnail_url"]); if(d)return d; const a=Array.isArray(row.detail_image_urls)?row.detail_image_urls:Array.isArray(row.image_urls)?row.image_urls:Array.isArray(row.images)?row.images:[]; return a.length?String(a[0]||""):"";}
export function detailProducts(row:ProductLike,opts?:{includeHidden?:boolean}):DetailProduct[]{const includeHidden=opts?.includeHidden??false; const note=parseProductNote(row); const names=detailNamesForProduct(row,true); if(!names.length)return []; const parentId=str(row,["id","product_id"]), parentName=str(row,["product_name","name","title"])||"상품", base=num(row,["price","sale_price","selling_price"]); const pricing=rec(note.option_pricing), hidden=new Set(arr(note.combo_hidden)), group=rec(note.brand_group), options=rec(group.detail_options), photos=rec(note.detail_photos), sets=rec(note.detail_photo_sets), managed=note.stock_management_enabled===true, raws=Array.isArray(note.stock_variants)?note.stock_variants as Array<Record<string,unknown>>:[]; return names.filter(n=>includeHidden||!hidden.has(n)).map(name=>{const o=rec(options[name]), colors=cleanOptionValues(o.colors), sizes=cleanOptionValues(o.sizes), set=arr(sets[name]), fallback=typeof photos[name]==="string"?String(photos[name]):"", images=[...new Set([...set,fallback].filter(Boolean))]; const pf=directImage(row); if(!images.length&&pf)images.push(pf); const variants=raws.map(v=>({rawColor:String(v?.color??"").trim(),size:String(v?.size??"").trim(),stock:Number(v?.stock??0)||0})).filter(v=>v.rawColor===name||v.rawColor.startsWith(`${name} / `)).map(v=>({color:v.rawColor===name?"":v.rawColor.slice(`${name} / `.length).trim(),size:EMPTY.has(v.size.toLowerCase())?"":v.size,stock:v.stock})); const stock=managed&&variants.length?variants.reduce((s,v)=>s+Math.max(0,v.stock),0):null; const plus=Number(pricing[name]??0); return {parentId,parentName,detailName:name,code:detailCode(name),hidden:hidden.has(name),price:Math.max(0,base+(Number.isFinite(plus)?plus:0)),images,image:images[0]||"",colors,sizes,stockManaged:managed,stockVariants:variants,stock};});}
export function expandForWidget(row:ProductLike):ProductLike[]{const details=detailProducts(row,{includeHidden:false}); if(!details.length)return [row]; const note=parseProductNote(row); return details.map(d=>({...row,product_name:d.detailName,price:d.price,image_url:d.image||row.image_url||null,color_options:d.colors,size_options:d.sizes,stock:d.stock??row.stock,total_stock:d.stock??row.total_stock,product_note:{...note,stock_variants:d.stockVariants},__parent_product_id:d.parentId,__detail_name:d.detailName,__detail_code:d.code}));}
export function adminDetailSearch(row:ProductLike,qraw:string){const q=String(qraw||"").replace(/\s+/g,"").toLowerCase(); if(!q)return []; return detailProducts(row,{includeHidden:true}).filter(d=>[d.detailName,d.code,...d.colors,...d.sizes].join(" ").replace(/\s+/g,"").toLowerCase().includes(q));}
export function buildDetailChatLine(d:DetailProduct){const p=[d.detailName,`${Math.round(d.price).toLocaleString("ko-KR")}원`]; if(d.colors.length)p.push(`색상: ${d.colors.join(",")}`); if(d.sizes.length)p.push(`사이즈: ${d.sizes.join(",")}`); return p.join(" / ").replace(/[\r\n]+/g," ").trim();}
function detailDescriptionWithoutCode(d:DetailProduct){let v=String(d.detailName||"").trim().replace(/^\S+\s*/,"").trim(); const c=d.colors[0]||""; if(c){const e=c.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"); v=v.replace(new RegExp(`\\s*[·/\\-]?\\s*${e}\\s*$`,"i"),"").trim();}return v||"상품";}
function commonDescription(ms:DetailProduct[]){const vals=ms.map(detailDescriptionWithoutCode).filter(Boolean); if(!vals.length)return "상품"; if(vals.every(v=>v===vals[0]))return vals[0]; const rows=vals.map(v=>v.split(/\s+/).filter(Boolean)), min=Math.min(...rows.map(r=>r.length)), common:string[]=[]; for(let i=0;i<min;i++){const t=rows[0][i]; if(!rows.every(r=>r[i]===t))break; common.push(t);} return common.join(" ").trim()||"같은 디자인";}
export function resolveDesignGroups(row:ProductLike):Array<{id:string;title:string;members:DetailProduct[]}>{const note=parseProductNote(row); const raw=Array.isArray(note.design_groups)?note.design_groups as Array<Record<string,unknown>>:[]; if(!raw.length)return []; const map=new Map(detailProducts(row,{includeHidden:false}).map(d=>[d.detailName,d])); return raw.map((g,i)=>{const members=arr(g.members).map(n=>map.get(n)).filter(Boolean) as DetailProduct[]; const codes=members.map(m=>m.code).filter(Boolean); return {id:String(g.id||`design-${i+1}`),title:String(g.title||`${codes.join("·")} ${commonDescription(members)}`).trim(),members};}).filter(g=>g.members.length>=2);}
export function buildDesignGroupChatText(group:{id?:string;title?:string;members:Array<Pick<DetailProduct,"detailName"|"code"|"price"|"colors"|"sizes">>}):string{const members=Array.isArray(group?.members)?group.members:[]; if(!members.length)return ""; const description=commonDescription(members as DetailProduct[]); const prices=members.map(m=>Math.max(0,Math.round(Number(m.price)||0))); const samePrice=prices.every(v=>v===prices[0]); const sizeLists=members.map(m=>cleanOptionValues(m.sizes)); const sizeKeys=sizeLists.map(v=>v.join("\u001f")); const sameSizes=sizeKeys.every(v=>v===sizeKeys[0]); const commonSizes=sameSizes?sizeLists[0]:[]; const itemSeparator=sameSizes?" · ":" / "; const optionText=members.map((m,i)=>{const code=String(m.code||"").trim()||detailCode(String(m.detailName||""))||`옵션${i+1}`; const color=cleanOptionValues(m.colors)[0]||""; const parts=[[code,color].filter(Boolean).join(" ")]; if(!sameSizes&&sizeLists[i].length)parts.push(`사이즈 ${sizeLists[i].join(",")}`); if(!samePrice)parts.push(`${prices[i].toLocaleString("ko-KR")}원`); return parts.filter(Boolean).join(" · ");}).join(itemSeparator); const sizeTail=commonSizes.length?` | 공통 사이즈 ${commonSizes.join(",")}`:""; const priceTail=samePrice?` | 각 ${prices[0].toLocaleString("ko-KR")}원`:""; return `✅ 현재상품 ✅ ${description} | ${optionText}${sizeTail}${priceTail}`.replace(/\s+/g," ").trim();}
