-- 특정 장바구니 한 건에만 적용하는 일회성 입금계좌 지정.
-- 전역 기존/신규회원 라우팅은 그대로 두고, 관리자가 명시한 현재 장바구니 주문 한 건만 덮어쓴다.

alter table public.cart_reservations add column if not exists kakao_id text;
alter table public.orders add column if not exists payment_bank_assignment_source text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.orders'::regclass
      and conname = 'orders_payment_bank_assignment_source_check'
  ) then
    alter table public.orders
      add constraint orders_payment_bank_assignment_source_check
      check (payment_bank_assignment_source is null or payment_bank_assignment_source in ('cart_override'));
  end if;
end
$$;

comment on column public.orders.payment_bank_assignment_source is
'cart_override면 관리자 장바구니 화면에서 해당 장바구니 주문 한 건에만 지정한 계좌. null은 기존 전역 라우팅.';

create table if not exists public.cart_bank_account_overrides (
  id bigint generated by default as identity primary key,
  session_key text not null,
  cart_started_at timestamptz not null,
  account_id text not null check (account_id in ('primary', 'secondary')),
  bank_name text not null,
  bank_account text not null,
  bank_holder text not null,
  status text not null default 'active' check (status in ('active', 'consumed', 'cancelled')),
  assigned_at timestamptz not null default now(),
  assigned_by text,
  consumed_at timestamptz,
  consumed_order_group_id text,
  cancelled_at timestamptz,
  unique (session_key, cart_started_at)
);

create index if not exists cart_bank_account_overrides_active_idx
  on public.cart_bank_account_overrides (session_key, cart_started_at)
  where status = 'active';

alter table public.cart_bank_account_overrides enable row level security;
comment on table public.cart_bank_account_overrides is
'관리자가 지정한 현재 장바구니 한 건의 계좌 스냅샷. 고객 브라우저 직접 접근 금지, 서버 service_role 전용.';

-- 전역 계좌 라우팅의 「같은 방송 계좌 유지」에서 일회성 장바구니 예외 주문은 제외한다.
-- 예외 주문이 다음 주문의 기준계좌로 전파되거나 서로 다른 계좌 충돌로 판정되는 것을 막는다.
alter function public.submit_customer_order_with_bank_routing(jsonb, integer, text, text, text, text, text)
  rename to submit_customer_order_with_bank_routing_base_v1;

do $$
declare
  v_definition text;
  v_changed text;
  v_needle_first text := 'and o.customer_order_segment is not null
      and o.payment_bank_account_id is not null';
  v_replacement_first text := 'and coalesce(o.payment_bank_assignment_source, '''') <> ''cart_override''
      and o.customer_order_segment is not null
      and o.payment_bank_account_id is not null';
  v_needle_second text := 'and o.customer_order_segment is not null
        and o.payment_bank_account_id is not null';
  v_replacement_second text := 'and coalesce(o.payment_bank_assignment_source, '''') <> ''cart_override''
        and o.customer_order_segment is not null
        and o.payment_bank_account_id is not null';
  v_first_hits integer;
  v_second_hits integer;
begin
  select pg_get_functiondef(
    'public.submit_customer_order_with_bank_routing_base_v1(jsonb,integer,text,text,text,text,text)'::regprocedure
  ) into v_definition;

  v_first_hits := (length(v_definition) - length(replace(v_definition, v_needle_first, ''))) / length(v_needle_first);
  v_second_hits := (length(v_definition) - length(replace(v_definition, v_needle_second, ''))) / length(v_needle_second);
  if v_first_hits <> 1 or v_second_hits <> 1 then
    raise exception '계좌 라우팅 기준 함수의 같은 방송 조건을 안전하게 갱신하지 못했습니다. 첫 조건=%, 두 번째 조건=%', v_first_hits, v_second_hits;
  end if;

  v_changed := replace(v_definition, v_needle_first, v_replacement_first);
  v_changed := replace(v_changed, v_needle_second, v_replacement_second);
  execute v_changed;
end
$$;

create or replace function public.submit_customer_order_with_bank_routing(
  p_order_rows jsonb,
  p_point_use_amount integer default 0,
  p_customer_phone text default null,
  p_youtube_nickname text default null,
  p_customer_name text default null,
  p_session_key text default null,
  p_kakao_id text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $function$
declare
  v_now timestamptz := now();
  v_group_id text;
  v_cart_started_at timestamptz;
  v_override public.cart_bank_account_overrides%rowtype;
  v_result jsonb;
  v_is_duplicate boolean := false;
begin
  v_group_id := nullif(trim(coalesce(p_order_rows->0->>'order_group_id', '')), '');

  -- 제출 RPC가 장바구니 홀드를 지우기 전에 현재 장바구니 시작시각과 지정계좌를 잠근다.
  if nullif(trim(coalesce(p_session_key, '')), '') is not null then
    select min(r.created_at)
      into v_cart_started_at
    from public.cart_reservations r
    where r.session_key = trim(p_session_key)
      and r.expires_at > v_now;

    if v_cart_started_at is not null then
      select o.* into v_override
      from public.cart_bank_account_overrides o
      where o.session_key = trim(p_session_key)
        and o.cart_started_at = v_cart_started_at
        and o.status = 'active'
      for update;
    end if;
  end if;

  v_result := public.submit_customer_order_with_bank_routing_base_v1(
    p_order_rows,
    p_point_use_amount,
    p_customer_phone,
    p_youtube_nickname,
    p_customer_name,
    p_session_key,
    p_kakao_id
  );

  begin
    v_is_duplicate := coalesce((v_result->>'duplicate')::boolean, false);
  exception when others then
    v_is_duplicate := false;
  end;

  -- 새로 저장된 정확히 이 주문에만 관리자 지정 스냅샷을 덮어쓰고 즉시 사용완료 처리한다.
  -- 같은 주문 재시도는 이미 orders에 저장된 스냅샷을 base 함수가 그대로 반환한다.
  if v_override.id is not null and not v_is_duplicate and v_group_id is not null then
    update public.orders
       set payment_bank_account_id = v_override.account_id,
           payment_bank_name = v_override.bank_name,
           payment_bank_account = v_override.bank_account,
           payment_bank_holder = v_override.bank_holder,
           payment_bank_assigned_at = v_now,
           payment_bank_assignment_source = 'cart_override'
     where order_group_id = v_group_id;

    if not found then
      raise exception '장바구니 지정계좌를 적용할 주문을 찾지 못했습니다.';
    end if;

    update public.cart_bank_account_overrides
       set status = 'consumed',
           consumed_at = v_now,
           consumed_order_group_id = v_group_id
     where id = v_override.id
       and status = 'active';

    if not found then
      raise exception '장바구니 지정계좌가 이미 사용되었거나 취소되었습니다.';
    end if;

    v_result := coalesce(v_result, '{}'::jsonb) || jsonb_build_object(
      'bank_account', jsonb_build_object(
        'id', v_override.account_id,
        'bankName', v_override.bank_name,
        'bankAccount', v_override.bank_account,
        'bankHolder', v_override.bank_holder
      ),
      'bank_assignment_source', 'cart_override'
    );
  end if;

  return v_result;
end;
$function$;

revoke execute on function public.submit_customer_order_with_bank_routing(jsonb, integer, text, text, text, text, text) from public;
revoke execute on function public.submit_customer_order_with_bank_routing(jsonb, integer, text, text, text, text, text) from anon;
revoke execute on function public.submit_customer_order_with_bank_routing(jsonb, integer, text, text, text, text, text) from authenticated;
grant execute on function public.submit_customer_order_with_bank_routing(jsonb, integer, text, text, text, text, text) to service_role;

-- 장바구니 목록의 신규/기존회원 표시는 최종 계좌 라우팅과 같은 유효주문 기준을 쓴다.
create or replace function public.admin_cart_customer_order_meta(p_identities jsonb)
returns table (
  session_key text,
  is_registered boolean,
  valid_order_count bigint,
  last_order_at timestamptz
)
language sql
security invoker
set search_path = public, pg_temp
as $function$
  with identity_rows as (
    select
      left(trim(coalesce(item->>'sessionKey', '')), 80) as session_key,
      regexp_replace(coalesce(item->>'phone', ''), '[^0-9]', '', 'g') as phone,
      trim(coalesce(item->>'kakaoId', '')) as kakao_id
    from jsonb_array_elements(coalesce(p_identities, '[]'::jsonb)) item
    where trim(coalesce(item->>'sessionKey', '')) <> ''
  )
  select
    i.session_key,
    exists (
      select 1 from public.customers c
      where (i.kakao_id <> '' and trim(coalesce(c.kakao_id, '')) = i.kakao_id)
         or (i.phone <> '' and regexp_replace(coalesce(c.customer_phone, ''), '[^0-9]', '', 'g') = i.phone)
    ) as is_registered,
    coalesce(stats.valid_order_count, 0)::bigint as valid_order_count,
    stats.last_order_at
  from identity_rows i
  left join lateral (
    select count(distinct coalesce(nullif(trim(o.order_group_id), ''), o.id::text))::bigint as valid_order_count,
           max(o.created_at) as last_order_at
    from public.orders o
    where o.is_deleted is distinct from true
      and o.is_test_order is distinct from true
      and lower(concat_ws(' ', o.order_manage_status, o.order_status, o.admin_status, o.admin_order_status_v2)) !~ '취소|환불|cancel|refund'
      and (
        (i.kakao_id <> '' and (
          trim(coalesce(o.kakao_id, '')) = i.kakao_id
          or (trim(coalesce(o.kakao_id, '')) = '' and i.phone <> '' and regexp_replace(coalesce(o.customer_phone, o.phone, ''), '[^0-9]', '', 'g') = i.phone)
        ))
        or (i.kakao_id = '' and i.phone <> '' and regexp_replace(coalesce(o.customer_phone, o.phone, ''), '[^0-9]', '', 'g') = i.phone)
      )
  ) stats on true;
$function$;

revoke execute on function public.admin_cart_customer_order_meta(jsonb) from public;
revoke execute on function public.admin_cart_customer_order_meta(jsonb) from anon;
revoke execute on function public.admin_cart_customer_order_meta(jsonb) from authenticated;
grant execute on function public.admin_cart_customer_order_meta(jsonb) to service_role;
