alter table public.cart_reservations
  add column if not exists product_name text,
  add column if not exists detail_name text,
  add column if not exists unit_price integer;

create table if not exists public.customer_site_alerts (
  id bigint generated by default as identity primary key,
  target_session_key text not null,
  customer_phone text,
  kind text not null default 'checkout_reminder',
  title text not null,
  message text not null,
  is_active boolean not null default true,
  seen_at timestamptz,
  dismissed_at timestamptz,
  expires_at timestamptz not null default (now() + interval '4 hours'),
  sent_by text,
  created_at timestamptz not null default now()
);
alter table public.customer_site_alerts enable row level security;
create index if not exists idx_customer_site_alerts_session_active on public.customer_site_alerts (target_session_key,is_active,expires_at desc);
create index if not exists idx_customer_site_alerts_phone_active on public.customer_site_alerts (customer_phone,is_active,expires_at desc) where customer_phone is not null;
create index if not exists idx_customer_site_alerts_recent_kind on public.customer_site_alerts (target_session_key,kind,created_at desc);
